# Generated by Django 5.2.1 on 2025-05-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_teacher_model'),
    ]

    operations = [
    ]
