# Generated by Django 5.2.1 on 2025-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_teacher_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
